export const CATEGORIES = [
  'Food & Dining',
  'Shopping',
  'Transportation',
  'Bills & Utilities',
  'Entertainment',
  'Healthcare',
  'Education',
  'Travel',
  'Salary',
  'Investment',
  'Gift',
  'Loan',
  'Insurance',
  'Savings',
  'Donation',
  'Freelance',
  'Gift Card',
  'Other'
] as const

export const FILTER_CATEGORIES = [
  'All Categories',
  'Food & Dining',
  'Shopping',
  'Transportation',
  'Bills & Utilities',
  'Entertainment',
  'Healthcare',
  'Education',
  'Travel',
  'Salary',
  'Investment',
  'Gift',
  'Loan',
  'Insurance',
  'Savings',
  'Donation',
  'Freelance',
  'Gift Card',
  'Other'
] as const
