export {}

declare global {
  /**
   * Represents a financial transaction (income or expense)
   */
  interface Transaction {
    /** Unique identifier (auto-generated by SQLite) */
    id?: number
    /** Type of transaction: income or expense */
    transaction_type: 'expense' | 'income'
    /** Short name/label for the transaction */
    name: string
    /** Amount in the user's selected currency */
    amount: number
    /** Category for grouping (e.g., 'Food', 'Transport', 'Salary') */
    category: string
    /** Optional longer description */
    description?: string
    /** Transaction date in ISO 8601 format (YYYY-MM-DD) */
    date: string
  }

  /**
   * Filter parameters for querying transactions
   */
  interface TransactionFilters {
    /** Filter by month (1-12), null for no filter */
    month: number | null
    /** Filter by year (e.g., 2024), null for no filter */
    year: number | null
    /** Search keyword for name/description fields */
    keyword: string | null
    /** Filter by specific category */
    category: string | null
    /** Maximum number of results (pagination) */
    limit?: number
    /** Number of results to skip (pagination offset) */
    offset?: number
    /** Column to sort by */
    sortColumn?: string
    /** Sort direction: ascending or descending */
    sortDirection?: 'asc' | 'desc'
  }

  /**
   * Paginated response containing transactions and total count
   */
  interface PaginatedTransactions {
    /** Array of transaction objects */
    transactions: Transaction[]
    /** Total number of transactions matching filters */
    total: number
  }

  /**
   * Monthly financial summary (income and expenses)
   */
  interface MonthlyTotal {
    /** Month number (1-12) */
    month: number
    /** Total income for the month */
    income: number
    /** Total expenses for the month */
    expense: number
  }

  /**
   * Filter parameters for monthly total queries
   */
  interface MonthlyTotalFilters {
    /** Month to aggregate (1-12) */
    month: number
    /** Year to aggregate (e.g., 2024) */
    year: number
  }

  /**
   * Single year value from database
   */
  interface GetYear {
    /** Year value */
    year: number
  }

  /**
   * Category breakdown with percentage
   */
  interface CategoryPercentage {
    /** Category name */
    category: string
    /** Total amount for this category */
    category_count: number
    /** Percentage of total (0-100) */
    percentage: number
  }

  /**
   * Filter parameters for category percentage queries
   */
  interface CategoryPerecentageFilters {
    /** Year to aggregate */
    year: number
    /** Month to aggregate (1-12) */
    month: number
    /** Transaction type to filter */
    type: 'income' | 'expense'
  }

  /**
   * Currency information for display
   */
  export type Currency = {
    /** ISO 4217 currency code (e.g., 'USD', 'EUR') */
    code: string
    /** Currency symbol (e.g., '$', '€') */
    symbol: string
    /** Full currency name */
    name: string
  }

  /**
   * API exposed to renderer via preload script
   */
  interface WindowAPI {
    /** Operating system ('win32', 'darwin', 'linux') */
    platform: NodeJS.Platform
    /** Controls titlebar dimming on Windows */
    dimTitlebar: (isDimmed: boolean, theme: 'light' | 'dark') => void
    /** Sets titlebar theme on Windows */
    setTitlebarTheme: (theme: 'light' | 'dark') => void
    /** Retrieves paginated transactions */
    getTransactions: (filters: TransactionFilters) => Promise<PaginatedTransactions>
    /** Creates a new transaction */
    addTransaction: (transaction: Transaction) => Promise<void>
    /** Deletes a transaction by ID */
    deleteTransaction: (transactionId: string) => Promise<void>
    /** Updates an existing transaction */
    updateTransaction: (transaction: Transaction) => Promise<void>
    /** Retrieves recent transactions */
    getRecentTransactions: (limit: number) => Promise<Transaction[]>
    /** Gets monthly totals */
    getMonthlyTotal: (filters: MonthlyTotalFilters) => Promise<MonthlyTotal>
    /** Retrieves single transaction by ID */
    getTransactionById: (id: number) => Promise<Transaction | null>
    /** Gets yearly data for all 12 months */
    getFullMonthlyTotal: (
      year: number
    ) => Promise<{ month: number; income: number; expense: number }[] | undefined>
    /** Gets available years with data */
    getAvailableYears: () => Promise<{ year: number }[]>
    /** Gets category breakdown percentages */
    getCategoryPercentage: (
      filters: CategoryPerecentageFilters
    ) => Promise<CategoryPercentage[] | null>
    /** Deletes all transactions */
    resetTable: () => Promise<void>
  }

  /** Window object extended with Reledger API */
  interface Window {
    api: WindowAPI
  }

  /**
   * Response from time.now timezone API
   */
  interface TimeResponse {
    /** ISO 8601 datetime string */
    datetime: string
    /** Unix timestamp */
    unixtime: number
    /** Timezone identifier */
    timezone: string
  }
}
